### ISSUE TITLE
Broken links (Theme Downloads)

### ISSUE THREAD

**Issue by dionweb** [surajmandalcell/Gtk-Theming-Guide#10]
The links on [:point_right: Theme Downloads](https://gtkthemingguide.now.sh/#/creating_gtk_themes?id=theme-downloads) section do not work.

>We're sorry. Unfortunately the page you were looking for could not be found. It may be temporarily unavailable, moved or no longer exist. Check the URL you entered for any mistakes and try again. Still >no luck? Search for whatever is missing, or take a look around the rest of our site.

**Comment by surajmandalcell** [comment]
They updated their website and most of the links don't work anymore :/
It'd be a pain to find a new link and update them.
