### ISSUE TITLE
https://gtkthemingguide.now.sh gives me only markdown

### ISSUE THREAD

**Issue by Vitexus** [surajmandalcell/Gtk-Theming-Guide#7]
Please render it to HTML

**Comment by surajmandalcell** [comment]
https://surajmandalcell.github.io/Gtk-Theming-Guide

Use this till then, don't know what broke in .now.sh 🤦‍♂️

**Comment by Vitexus** [comment]
But https://gtkthemingguide-git-fork-vitexus-master.cruelplatypus67.now.sh/#/creating_gtk_themes is OK ... maybe it need fresh push of some minimal change to rebuild webpages ...

**Comment by surajmandalcell** [comment]
I guess it was an issue on the service end, https://gtkthemingguide.now.sh/ now works again for some reason :p
