### ISSUE TITLE
gtk-apps.org is totally unrelated

### ISSUE THREAD

**Issue by codic12** [surajmandalcell/Gtk-Theming-Guide#9]
The guide has this:
> This is a Python-based alternative to "The Widget Factory". PyWF can be obtained at http://gtk-apps.org/content/show.php/PyTWF?content=102024

That link takes you to the gtk-apps.org homepage, which I'm not even going to describe...

**Comment by surajmandalcell** [comment]
What the fuck, I'll remove the link tomorrow when I'm on my pc again.

**Comment by surajmandalcell** [comment]
What the heck happened to gtk-apps.org 😂😂

**Comment by codic12** [comment]
:+1: thanks a lot

**Comment by surajmandalcell** [comment]
should be fixed now

**Comment by codic12** [comment]
great
